# Generated by Django 4.0.6 on 2022-08-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_simple_url_project_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='src_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='src_url_name',
            field=models.CharField(blank=True, max_length=247, null=True),
        ),
    ]
