# Generated by Django 4.0.6 on 2022-08-08 01:39

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_src_url_project_src_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
