# Generated by Django 4.0.6 on 2022-08-09 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_status_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='img_projects')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.ManyToManyField(related_name='galleries', to='projects.image'),
        ),
    ]
