# Generated by Django 4.0.6 on 2022-08-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='logotype',
            field=models.ImageField(blank=True, null=True, upload_to='img_logotypes'),
        ),
    ]
