# Generated by Django 4.0.6 on 2022-08-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_options_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='Priority'),
        ),
    ]
