# Generated by Django 4.0.6 on 2022-10-11 08:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
                ('category_desc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=25)),
                ('task_desc', tinymce.models.HTMLField()),
                ('task_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whatido.taskcategory')),
            ],
        ),
    ]
