# Generated by Django 4.0.6 on 2022-10-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatido', '0002_alter_taskcategory_options_alter_task_task_category_and_more'),
        ('whatido', '0002_alter_taskcategory_options_taskcategory_priority_and_more'),
    ]

    operations = [
    ]
