# Generated by Django 4.0.6 on 2022-10-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatido', '0003_alter_task_options_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'ordering': ['taskcat_priority'], 'verbose_name_plural': 'Task Categories'},
        ),
        migrations.RenameField(
            model_name='taskcategory',
            old_name='priority',
            new_name='taskcat_priority',
        ),
    ]
