# Generated by Django 4.0.6 on 2022-10-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatido', '0004_alter_taskcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'ordering': ['priority'], 'verbose_name_plural': 'Task Categories'},
        ),
        migrations.RenameField(
            model_name='taskcategory',
            old_name='taskcat_priority',
            new_name='priority',
        ),
    ]
