# Generated by Django 4.0.6 on 2022-10-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatido', '0003_merge_20221014_2021'),
        ('whatido', '0005_alter_taskcategory_options_and_more'),
    ]

    operations = [
    ]
