# Generated by Django 4.0.6 on 2022-08-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='update',
        ),
    ]
