# Generated by Django 4.0.6 on 2022-10-11 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_rename_post_comment_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='updates.update'),
        ),
        migrations.AlterField(
            model_name='update',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
